### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "branch": "hw-09-aftermath",
  "accounts": "acc-12",
  "ratePerSecond": 1000,
  "testCount": 200000,
  "processingTimeMillis": 50000
}
### accountName=acc-12, parallelRequests=20000, rateLimitPerSec=1100, price=30, averageProcessingTime=PT10S, enabled=true)
### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}